# -*- coding: utf-8 -*-
"""Labsheet2FlickerImages.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13b1Ly0kctwJX89-HbF9TEFVehqO3OYBM
"""

import pandas as pd
import numpy as np
from functools import reduce

from google.colab import drive
df=pd.read_csv('/content/drive/MyDrive/dataset/BL-Flickr-Images-Book.csv')

print(df.head())

df.shape

type(df)

for col in df:
  print(col)

to_drop=['Edition Statement','Corporate Author','Corporate Contributors','Former owner','Engraver']
df.head()

for col in df.columns:
  print(col)

df.set_index('Identifier', inplace=True)
df['Date of Publication'].head(25)

unwanted_characters=['[',',','-']
def clean_dates(item):
  dop=str(item.loc['Date of Publication'])
  if dop == 'nan' or dop[0]=='[':
    return np.NaN
  for character in unwanted_characters:
    if character in dop:
      character_index=dop.find(character)
      dop=dop[:character_index]
    return dop
df['Date of Publication']=df.apply(clean_dates,axis=1)

df['Date of Publication'].head(25)

def clean_title(title):
  if title == 'nan':
    return 'NaN'
  if title[0] == '[':
    title=title[1:title.find(']')]
  if 'by' in title:
    title=title[:title.find('by')]
  if 'By' in title:
    title=title[:title.find('[')]
  title=title[:-2]
  title=list(map(str.capitalize,title.split()))
  return ''.join(title)
df['Title']=df['Title'].apply(clean_title)
df.head()